### ISSUE TITLE
Add Google Analytics to extension

### ISSUE THREAD

**Issue by JPedroBorges** [Room-Elephant/extension-chrome-key-retriever#31]

**Comment by Marianarodrigues7** [comment]
Done 🔥

**Comment by Marianarodrigues7** [comment]
| Event name | Event description | Parameters |
| ----------- | ----------- |----------- |
| page_view | Event when extension opens| version | 
| extension_error| Event when unhandled rejection| error reason | 
| number_of_keys| Event triggered in each store update| total (key list length); session (session items length); cookie (cookie items length);  local (local items length);| 
|view_value| Event when clicking view value|  | 
|copy_value| Event when clicking copy value|  | 
|set_value| Event when clicking set value|  | 
|delete_item| Event when clicking delete key|  | 
|invalid_form| Event when clicking save key, in add key form, with incorrect fields|invalidFields (stringified list of incorrect fields)  |
